# Generated by Django 4.1.4 on 2023-03-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdeteil_is_manager_division_userdeteil_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Название подразделения'),
        ),
        migrations.AlterField(
            model_name='userdeteil',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Руководитель?'),
        ),
    ]
