# Generated by Django 4.1.4 on 2023-03-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_division_name_alter_userdeteil_is_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdeteil',
            options={'verbose_name': 'Данные пользователя', 'verbose_name_plural': 'Данные пользователей'},
        ),
    ]
