# Generated by Django 4.2 on 2023-05-15 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userdeteil_options_alter_userdeteil_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdeteil',
            name='phone_number',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(3200), django.core.validators.MaxValueValidator(3399)], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='userdeteil',
            name='second_name',
            field=models.CharField(max_length=20, verbose_name='Отчество'),
        ),
    ]
