version: "3.9"

services:
  web-app:
    build: ./web-app
    container_name: web-app-Plans-and-Tasks
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - ./web-app:/home/app/web
    depends_on:
      - db
      - redis
      - worker
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    container_name: db-Plans-and-Tasks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    container_name: redis-Plans-and-Tasks
    ports:
      - "6379:6379"
    image: redis

  worker:
    container_name: worker-Plans-and-Tasks
    build: ./web-app
    command: celery -A config worker -l INFO
    volumes:
      - ./web-app:/home/app/web
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery-beat:
    container_name: celery-beat-Plans-and-Tasks
    build: ./web-app
    command: celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./web-app:/home/app/web
    depends_on:
      - db
      - redis
      - web-app
    env_file:
      - .env

  flower:
    container_name: flower-Plans-and-Tasks
    build: ./web-app
    command: celery -A config flower
    volumes:
      - ./web-app:/home/app/web
    depends_on:
      - db
      - redis
    ports:
      - "5555:5555"
    env_file:
      - .env

volumes:
  postgres_data:
