# Generated by Django 4.1.4 on 2023-03-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatternPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя шаблона плана')),
            ],
            options={
                'verbose_name': 'Шаблон План-графика',
                'verbose_name_plural': 'Шаблоны Планов-графиков',
            },
        ),
        migrations.CreateModel(
            name='PatternTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя шаблонной задачи')),
                ('dey_ofset', models.CharField(blank=True, help_text='Введите смещение: +1 -увеличить на один, -1 уменьшить на один, 1 фиксирования цыфра', max_length=4, null=True, verbose_name='Смещение дней')),
                ('month_ofset', models.CharField(blank=True, help_text='Введите смещение: +1 -увеличить на один, -1 уменьшить на один, 1 фиксирования цыфра', max_length=4, null=True, verbose_name='Смещение месяцев')),
                ('year_ofset', models.CharField(blank=True, help_text='Введите смещение: +1 -увеличить на один, -1 уменьшить на один, 1 фиксирования цыфра', max_length=4, null=True, verbose_name='Смещение лет')),
                ('pattern_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.patternplan', verbose_name='Шаблонный План-график')),
            ],
            options={
                'verbose_name': 'Шаблон задачи',
                'verbose_name_plural': 'Шаблоны задач',
            },
        ),
        migrations.CreateModel(
            name='Perfomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование подразделения')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя плана')),
                ('completion_date', models.DateField(verbose_name='Планируямая дата завершения')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_of_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'План-график',
                'verbose_name_plural': 'План-графики',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя задачи')),
                ('completion_date', models.DateField(verbose_name='Дата выполнения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная?')),
                ('pattern_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.patterntask', verbose_name='Шаблонная задача')),
                ('perfomer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plans.perfomer', verbose_name='Исполнитель')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan', verbose_name='План-график')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
