# Generated by Django 4.1.4 on 2023-03-01 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Имя группы')),
            ],
            options={
                'verbose_name': 'Группа задачи',
                'verbose_name_plural': 'Группы задач',
            },
        ),
        migrations.AlterModelOptions(
            name='patternplan',
            options={'verbose_name': 'Шаблон Плана-графика', 'verbose_name_plural': 'Шаблоны Планов-графиков'},
        ),
        migrations.AlterField(
            model_name='patternplan',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Имя шаблона плана'),
        ),
        migrations.AlterField(
            model_name='patterntask',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Имя шаблонной задачи'),
        ),
        migrations.AlterField(
            model_name='perfomer',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Наименование подразделения'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Имя плана'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Имя задачи'),
        ),
        migrations.AddField(
            model_name='patterntask',
            name='task_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.taskgroup', verbose_name='Группа задач'),
        ),
    ]
