# Generated by Django 4.1.4 on 2023-03-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_taskgroup_alter_patternplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternplan',
            name='name',
            field=models.TextField(verbose_name='Имя шаблона плана'),
        ),
        migrations.AlterField(
            model_name='patterntask',
            name='name',
            field=models.TextField(verbose_name='Имя шаблонной задачи'),
        ),
        migrations.AlterField(
            model_name='perfomer',
            name='name',
            field=models.TextField(verbose_name='Наименование подразделения'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.TextField(verbose_name='Имя плана'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.TextField(verbose_name='Имя задачи'),
        ),
    ]
