# Generated by Django 4.1.4 on 2023-03-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_patternplan_name_alter_patterntask_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgroup',
            name='name',
            field=models.TextField(verbose_name='Имя группы'),
        ),
    ]
