# Generated by Django 4.1.4 on 2023-03-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_alter_taskgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterntask',
            name='task_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.taskgroup', verbose_name='Группа задач'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Имя группы'),
        ),
    ]
