# Generated by Django 4.1.4 on 2023-03-01 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_alter_patterntask_task_group_alter_taskgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterntask',
            name='task_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.taskgroup', verbose_name='Группа задач'),
        ),
        migrations.AlterField(
            model_name='perfomer',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Наименование подразделения'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='name',
            field=models.TextField(verbose_name='Имя группы'),
        ),
    ]
