# Generated by Django 4.1.4 on 2023-03-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_alter_patterntask_task_group_alter_perfomer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternplan',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Имя шаблона плана'),
        ),
        migrations.AlterField(
            model_name='patterntask',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Имя шаблонной задачи'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Имя плана'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Имя задачи'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Имя группы'),
        ),
    ]
