# Generated by Django 4.1.4 on 2023-03-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_alter_patternplan_name_alter_patterntask_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='perfomer',
        ),
        migrations.AddField(
            model_name='patterntask',
            name='perfomer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='plans.perfomer', verbose_name='Исполнитель'),
            preserve_default=False,
        ),
    ]
