# Generated by Django 4.1.4 on 2023-03-14 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_remove_task_perfomer_patterntask_perfomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='pattern_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.patternplan', verbose_name='Шаблонный План-график'),
        ),
    ]
