# Generated by Django 4.1.4 on 2023-03-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_plan_pattern_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternplan',
            name='description',
            field=models.TextField(null=True, verbose_name='Имя шаблона плана'),
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(null=True, verbose_name='Имя плана'),
        ),
        migrations.AlterField(
            model_name='patternplan',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Краткое имя шаблона плана'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Краткое имя плана'),
        ),
    ]
