# Generated by Django 4.1.4 on 2023-03-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_patternplan_description_plan_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternplan',
            name='description',
            field=models.TextField(verbose_name='Имя шаблона плана'),
        ),
    ]
