# Generated by Django 4.1.4 on 2023-03-23 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userdeteil_options'),
        ('plans', '0016_task_perfomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='patterntask',
            name='divisin_perfomer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.division', verbose_name='Подразделение исполнителя'),
        ),
        migrations.AddField(
            model_name='perfomer',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.division', verbose_name='Подразделение исполнителя'),
        ),
        migrations.AddField(
            model_name='perfomer',
            name='performer_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.userdeteil', verbose_name='Исполнитель'),
        ),
    ]
