# Generated by Django 4.1.4 on 2023-03-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0018_plan_user_creator_plan_user_updater_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patterntask',
            name='perfomer',
        ),
    ]
