# Generated by Django 4.1.4 on 2023-03-23 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userdeteil_options'),
        ('plans', '0019_remove_patterntask_perfomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfomer',
            name='name',
        ),
        migrations.AlterField(
            model_name='plan',
            name='user_updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_updater', to='accounts.userdeteil', verbose_name='Последний редактор'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user_updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_updater', to='accounts.userdeteil', verbose_name='Последний редактор'),
        ),
    ]
