# Generated by Django 4.1.4 on 2023-03-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0020_remove_perfomer_name_alter_plan_user_updater_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='task',
            name='date_of_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
