# Generated by Django 4.1.4 on 2023-03-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0021_task_date_of_creation_task_date_of_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
