# Generated by Django 4.1.4 on 2023-03-30 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0022_alter_task_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.plan', verbose_name='План-график'),
        ),
    ]
