# Generated by Django 4.2 on 2023-04-19 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userdeteil_options_alter_userdeteil_division_and_more'),
        ('plans', '0023_alter_task_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterntask',
            name='days_ofset',
            field=models.CharField(default='0', help_text='Введите смещение дней: +1 -увеличить на один, -1 уменьшить на один, 1 фиксирования цыфра', max_length=4, verbose_name='Смещение дней'),
        ),
        migrations.AlterField(
            model_name='patterntask',
            name='months_ofset',
            field=models.CharField(default='0', help_text='Введите смещение месяцев: +1 -увеличить на один, -1 уменьшить на один, 1 фиксирования цыфра', max_length=4, verbose_name='Смещение месяцев'),
        ),
        migrations.AlterField(
            model_name='patterntask',
            name='task_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.taskgroup', verbose_name='Группа задач'),
        ),
        migrations.AlterField(
            model_name='patterntask',
            name='years_ofset',
            field=models.CharField(default='0', help_text='Введите смещение лет: +1 -увеличить на один, -1 уменьшить на один, 1 фиксирования цыфра', max_length=4, verbose_name='Смещение лет'),
        ),
        migrations.AlterField(
            model_name='perfomer',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.division', verbose_name='Подразделение исполнителя'),
        ),
        migrations.AlterField(
            model_name='perfomer',
            name='performer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.userdeteil', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pattern_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.patterntask', verbose_name='Шаблонная задача'),
        ),
        migrations.AlterField(
            model_name='task',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.plan', verbose_name='План-график'),
        ),
    ]
