# Generated by Django 4.2 on 2023-04-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userdeteil_options_alter_userdeteil_division_and_more'),
        ('plans', '0024_alter_patterntask_days_ofset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterntask',
            name='divisin_perfomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.division', verbose_name='Подразделение исполнителя'),
        ),
        migrations.AlterField(
            model_name='patterntask',
            name='task_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plans.taskgroup', verbose_name='Группа задач'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pattern_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plans.patterntask', verbose_name='Шаблонная задача'),
        ),
        migrations.AlterField(
            model_name='task',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan', verbose_name='План-график'),
        ),
    ]
