# Generated by Django 4.1.4 on 2023-05-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0025_alter_patterntask_divisin_perfomer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Краткое имя плана'),
        ),
    ]
